# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the
# server process.

# Theme Settings
remote_theme: "manid2/lone-wolf-theme"
bootswatch_theme: "united"

# These settings are always used by Jekyll
title: "Chapter of Democratic Socialists of America"
url: https://[dsachapter].dsachapters.org

# These settings ase used by the jekyll-seo-tag plugin. The plugin adds
# metadata tags for search engines and social networks to better index and
# display your siteâ€™s content. None of these are necessary, but will make your
# site more discoverable to others. See this link for more information:
# https://jekyll.github.io/jekyll-seo-tag/usage/
# The tagline is used when `page.title` is not defined.
tagline: "Homepage for our DSA Chapter"
# The description is used when a page doesn't provide its own description.
# It will also be used as the page's title tag if neither `page.title` nor
# `site.tagline` has been defined.
description: "Homepage for our DSA Chapter"
author: DSA
twitter:
  username: dsachapter
  # The site's default card type. See this link for more information:
  # https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards
  card: summary
facebook:
  # A Facebook app ID for Facebook insights: https://www.facebook.com/help/794890670645072/
  app_id: # 1234
  # A Facebook page URL or ID of the publishing entity. I don't know what this means.
  publisher: # 1234
  # A Facebook user ID for domain insights linked to a personal account. I don't know what this means.
  admins: # 1234
logo: assets/images/smalllogo.png # PNG is SEO friendly
social:
  name: Chapter of Democratic Socialists of America
  links:
    - https://twitter.com/dsachapter
    - https://www.facebook.com/dsachapter
    - https://www.instagram.com/dsachapter
    - https://www.github.com/dsachapter
# Site verifications
# I don't understand this yet, but maybe this page is helpful:
# https://support.google.com/webmasters/answer/9008080?hl=en
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234
  baidu: # 1234
locale: "en_US"

# comments settings
comments:
  provider: false # false (default), "disqus", "discourse"
  disqus:
    # refer what is disqus shortname article online
    shortname:

# feed
atom_feed:
  path: # blank (default) uses feed.xml

# site search settings
search: # true, false (default)
search_full_content: # true, false (default)
search_provider: # google

google:
  search_engine_id: # YOUR_SEARCH_ENGINE_ID
  instant_search: # false (default), true

# Analytics
analytics:
  provider: false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id:
    anonymize_ip: # true, false (default)

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore /docs in theme
  - /test # ignore /test in theme
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# site defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      show_hero: true
      show_author: true
      show_toc: true
      share: true
      show_comments: false
      show_ads: false
  # any page
  - scope:
      path: ""
    values:
      # for SEO and social sharing
      image: assets/images/smalllogo.png
      image_alt: Democratic Socialists of America logo
